import 'package:flutter_inappwebview/flutter_inappwebview.dart';

InAppWebViewController? dashBoardViewController;
InAppWebViewController? accountViewController;
InAppWebViewController? settingViewController;